Use printf instead of echo

diff --git a/archinstall b/archinstall
--- a/archinstall
+++ b/archinstall
@@ -9,13 +9,13 @@
 
 willexit=0
 
-[ "$(echo "$PWD" | sed 's/.*\///')" = "archinstall" ] || { 
-    echo "This script must be run from the root directory of the repository."
+[ "$(printf "%s\n" "$PWD" | sed 's/.*\///')" = "archinstall" ] || { 
+    printf "%s\n" "This script must be run from the root directory of the repository."
     willexit=1
 }
 
 [ "$6" = "" ] && { 
-    echo "You must call this script with at least 6 arguments: efi_partition, root_partition, home_partition, root_passwd, user, user_password."; printf "All arguments:\nefi_partition, root_partition, home_partition, root_passwd, user, user_passwd, wireless_security, wirelss_ssid, wireless_password, wireless_hidden\n"
+    printf "%s\n" "You must call this script with at least 6 arguments: efi_partition, root_partition, home_partition, root_passwd, user, user_password."; printf "All arguments:\nefi_partition, root_partition, home_partition, root_passwd, user, user_passwd, wireless_security, wirelss_ssid, wireless_password, wireless_hidden\n"
     willexit=1
 }
 
@@ -25,7 +25,7 @@ then
     then
         interface="$(iw dev | grep Interface | awk '{print $2}')"
         printf "Description='A simple %s encrypted wireless connection'\nInterface=$interface\nConnection=wireless\nSecurity=%s\nIP=dhcp\nESSID='%s'\nKey='%s'\n" "$7" "$7" "$8" "$9" > /etc/netctl/wirelessconf
-        [ "${10}" = "y" ] && echo "Hidden=yes" >> /etc/netctl/wirelessconf
+        [ "${10}" = "y" ] && printf "%s\n" "Hidden=yes" >> /etc/netctl/wirelessconf
         olddir="$(pwd)"
         cd /etc/netctl || exit 1
         netctl start wirelessconf || willexit=1
@@ -35,11 +35,11 @@ then
         then
             wireless=1
         else
-            echo "Could not connect to the internet."
+            printf "%s\n" "Could not connect to the internet."
             willexit=1
         fi
     else
-        echo "You are not connected to the internet."
+        printf "%s\n" "You are not connected to the internet."
         willexit=1
     fi
 fi
